version: '3'

services:

  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  oauth2:
    restart: always
    build:
        context: oauth20
        dockerfile: Dockerfile
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 9004:9004

  backend:
    restart: always
    build:
        context: backend
        dockerfile: Dockerfile
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 3004:3004

volumes:
  mongo: {}
